
import React, { useState, useMemo } from 'react';
import { BaseClaimData, User } from '../types';
import { 
  BarChart3, FileSpreadsheet, Send, Search, Filter, CalendarRange, 
  Activity, TrendingUp, DollarSign, CheckCircle2, ShieldAlert, Share2, 
  Building2, MapPin, Layers, Clock, X, ChevronRight, PieChart, Download,
  ArrowUpRight, Target, Zap
} from 'lucide-react';
import { COMPANIES, COMPANY_BRANCH_MAPPING, CLAIM_TYPES } from '../constants';

interface Props {
  claims: BaseClaimData[];
  currentUser: User | null;
  isGlobal?: boolean;
}

const ReportConsole: React.FC<Props> = ({ claims, currentUser, isGlobal }) => {
  const [filterCompany, setFilterCompany] = useState('');
  const [filterBranch, setFilterBranch] = useState('');
  const [filterType, setFilterType] = useState('');
  const [filterStatus, setFilterStatus] = useState('');
  const [startDate, setStartDate] = useState('');
  const [endDate, setEndDate] = useState('');

  const filteredClaims = useMemo(() => {
    return claims.filter(c => {
      if (filterCompany && c.company !== filterCompany) return false;
      if (filterBranch && c.branch !== filterBranch) return false;
      if (filterType && c.claimType !== filterType) return false;
      if (filterStatus && c.status !== filterStatus) return false;
      
      if (startDate) {
        const start = new Date(startDate).getTime();
        if (c.timestamp < start) return false;
      }
      if (endDate) {
        const end = new Date(endDate);
        end.setHours(23, 59, 59, 999);
        if (c.timestamp > end.getTime()) return false;
      }
      return true;
    });
  }, [claims, filterCompany, filterBranch, filterType, filterStatus, startDate, endDate]);

  const stats = useMemo(() => {
    const total = filteredClaims.length;
    const totalAmount = filteredClaims.reduce((acc, curr) => acc + parseFloat((curr.loanAmount || '0').replace(/,/g, '')), 0);
    const approved = filteredClaims.filter(c => ['Approved', 'Cash Requested', 'Completed'].includes(c.status)).length;
    const rejected = filteredClaims.filter(c => c.status === 'Rejected').length;
    
    const efficiency = total > 0 ? Math.round((approved / total) * 100) : 0;
    
    return { total, totalAmount, approved, rejected, efficiency };
  }, [filteredClaims]);

  const handleExportCSV = () => {
    const headers = ["ID", "Date", "Customer", "Loan No", "Entity", "Station", "Type", "Status", "Amount"];
    const rows = filteredClaims.map(c => [
      c.id,
      new Date(c.timestamp).toLocaleDateString(),
      c.customerName,
      c.loanNumber,
      c.company,
      c.branch,
      c.claimType,
      c.status,
      c.loanAmount
    ]);
    
    const csvContent = [headers, ...rows].map(e => e.join(",")).join("\n");
    const blob = new Blob([csvContent], { type: 'text/csv;charset=utf-8;' });
    const url = URL.createObjectURL(blob);
    const link = document.createElement("a");
    link.setAttribute("href", url);
    link.setAttribute("download", `Executive_Report_${new Date().toISOString().slice(0,10)}.csv`);
    link.click();
  };

  const handleWhatsAppSummary = () => {
    let message = `*MONIK GROUP - EXECUTIVE REPORT SUMMARY*\n`;
    message += `Date Scope: ${startDate || 'N/A'} to ${endDate || 'N/A'}\n`;
    message += `--------------------------------\n`;
    message += `Entity: ${filterCompany || 'ALL'}\n`;
    message += `Station: ${filterBranch || 'ALL'}\n`;
    message += `Product: ${filterType || 'ALL'}\n`;
    message += `--------------------------------\n`;
    message += `Total Volume: ${stats.total} Units\n`;
    message += `Aggregate Value: LKR ${stats.totalAmount.toLocaleString()}\n`;
    message += `Approved/Processed: ${stats.approved}\n`;
    message += `Registry Rejections: ${stats.rejected}\n`;
    message += `Efficiency Ratio: ${stats.efficiency}%\n`;
    message += `--------------------------------\n`;
    message += `Generated By: ${currentUser?.name || 'System Auditor'}\n`;
    message += `Module: Report Studio v5.0`;

    const url = `https://wa.me/?text=${encodeURIComponent(message)}`;
    window.open(url, '_blank');
  };

  const labelClass = "text-[9px] font-black text-slate-500 uppercase tracking-[0.25em] block mb-2.5 ml-1";
  const inputClass = "w-full bg-slate-900 border border-white/10 rounded-xl p-3.5 text-xs font-black uppercase text-white focus:ring-2 focus:ring-blue-600 transition-all outline-none shadow-sm cursor-pointer hover:bg-slate-800";

  return (
    <div className="space-y-10 animate-in fade-in duration-700 pb-40 bg-black -mx-10 -my-10 p-10 min-h-screen">
      
      {/* HEADER PROTOCOL */}
      <div className="flex flex-col md:flex-row md:items-center justify-between gap-8 mb-4">
        <div className="flex items-center gap-6">
            <div className="bg-slate-900 p-5 rounded-[2rem] text-blue-400 shadow-[0_0_50px_-12px_rgba(59,130,246,0.4)] rotate-[-2deg] border-b-4 border-blue-600">
                <PieChart size={32} />
            </div>
            <div>
                <h1 className="text-5xl font-black text-white uppercase tracking-tighter leading-none">Report Studio</h1>
                <p className="text-[10px] font-black text-slate-500 uppercase tracking-[0.5em] mt-3 ml-1">Analytical Operations Console</p>
            </div>
        </div>
        <div className="flex gap-4">
             <button 
                onClick={handleWhatsAppSummary}
                className="bg-emerald-600 text-slate-950 px-8 py-4 rounded-2xl font-black text-[11px] uppercase tracking-widest shadow-xl flex items-center gap-3 hover:bg-emerald-500 transition-all active:scale-95"
             >
                <Share2 size={18} /> WhatsApp Summary
             </button>
             <button 
                onClick={handleExportCSV}
                className="bg-white text-slate-950 px-8 py-4 rounded-2xl font-black text-[11px] uppercase tracking-widest shadow-xl flex items-center gap-3 hover:bg-slate-100 transition-all active:scale-95"
             >
                <FileSpreadsheet size={18} /> Export Excel/CSV
             </button>
        </div>
      </div>

      {/* INTELLIGENCE FILTERS */}
      <div className="bg-slate-950 p-10 rounded-[3.5rem] shadow-[0_0_80px_-20px_rgba(0,0,0,1)] border border-white/5 space-y-10">
          <div className="flex items-center gap-3 pb-6 border-b border-white/5">
              <Filter className="text-blue-500" size={20} />
              <h3 className="text-sm font-black uppercase text-blue-400 tracking-widest">Multi-Parameter Matrix Matrix</h3>
          </div>

          <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-4 gap-8">
              <div>
                <label className={labelClass}>Operating Entity</label>
                <select className={inputClass} value={filterCompany} onChange={e => {setFilterCompany(e.target.value); setFilterBranch('');}}>
                    <option value="" className="bg-black text-white">All Organizations</option>
                    {COMPANIES.map(c => <option key={c} value={c} className="bg-black text-white">{c}</option>)}
                </select>
              </div>
              <div>
                <label className={labelClass}>Station Node</label>
                <select className={inputClass} value={filterBranch} onChange={e => setFilterBranch(e.target.value)} disabled={!filterCompany}>
                    <option value="" className="bg-black text-white">All Branches</option>
                    {(filterCompany ? (COMPANY_BRANCH_MAPPING[filterCompany] || []) : []).map(b => <option key={b} value={b} className="bg-black text-white">{b}</option>)}
                </select>
              </div>
              <div>
                <label className={labelClass}>Workflow Status</label>
                <select className={inputClass} value={filterStatus} onChange={e => setFilterStatus(e.target.value)}>
                    <option value="" className="bg-black text-white">Any Status</option>
                    <option value="Requested" className="bg-black text-white">Requested</option>
                    <option value="Approved" className="bg-black text-white">Approved</option>
                    <option value="Completed" className="bg-black text-white">Completed</option>
                    <option value="Rejected" className="bg-black text-white">Rejected</option>
                </select>
              </div>
              <div>
                <label className={labelClass}>Product Classification</label>
                <select className={inputClass} value={filterType} onChange={e => setFilterType(e.target.value)}>
                    <option value="" className="bg-black text-white">All Products</option>
                    {CLAIM_TYPES.map(t => <option key={t.value} value={t.value} className="bg-black text-white">{t.label.toUpperCase()}</option>)}
                </select>
              </div>
          </div>

          <div className="bg-white/5 p-8 rounded-[2.5rem] border border-white/5 shadow-inner">
              <div className="flex items-center gap-2 mb-6 text-[10px] font-black text-blue-400 uppercase tracking-widest">
                <CalendarRange size={16} /> TEMPORAL SCOPE SELECTION (Epoch)
              </div>
              <div className="grid grid-cols-1 md:grid-cols-2 gap-8">
                <div className="relative">
                    <label className="absolute -top-2 left-4 bg-slate-900 px-2 text-[8px] font-black text-slate-500 uppercase z-10 tracking-widest">EPOCH START</label>
                    <input 
                        type="date" 
                        className="w-full bg-slate-950 border border-white/10 rounded-2xl p-4 text-xs font-black uppercase text-white focus:ring-2 focus:ring-blue-600 outline-none shadow-sm h-[52px]" 
                        value={startDate} 
                        onChange={e => setStartDate(e.target.value)} 
                    />
                </div>
                <div className="relative">
                    <label className="absolute -top-2 left-4 bg-slate-900 px-2 text-[8px] font-black text-slate-500 uppercase z-10 tracking-widest">EPOCH END</label>
                    <input 
                        type="date" 
                        className="w-full bg-slate-950 border border-white/10 rounded-2xl p-4 text-xs font-black uppercase text-white focus:ring-2 focus:ring-blue-600 outline-none shadow-sm h-[52px]" 
                        value={endDate} 
                        onChange={e => setEndDate(e.target.value)} 
                    />
                </div>
              </div>
          </div>
      </div>

      {/* METRIC ANALYSIS CARDS */}
      <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-4 gap-8">
         {[
           { label: 'Object Volume', value: stats.total, icon: <Layers />, color: 'text-blue-400', bg: 'bg-blue-500/10' },
           { label: 'Aggregate Value', value: `LKR ${stats.totalAmount.toLocaleString()}`, icon: <DollarSign />, color: 'text-emerald-400', bg: 'bg-emerald-500/10' },
           { label: 'Approval KPI', value: `${stats.efficiency}%`, icon: <Activity />, color: 'text-indigo-400', bg: 'bg-indigo-500/10' },
           { label: 'Risk Flags', value: stats.rejected, icon: <ShieldAlert />, color: 'text-red-400', bg: 'bg-red-500/10' }
         ].map((stat, i) => (
            <div key={i} className="bg-slate-900/50 backdrop-blur-md p-8 rounded-[2.5rem] shadow-2xl border border-white/5 flex items-center gap-6 group hover:border-emerald-500/30 transition-all duration-500">
                <div className={`p-4 rounded-3xl ${stat.bg} ${stat.color} shadow-lg transition-transform group-hover:scale-110 group-hover:rotate-3`}>
                    {React.cloneElement(stat.icon as React.ReactElement<any>, { size: 24 })}
                </div>
                <div>
                    <p className="text-[9px] font-black text-slate-500 uppercase tracking-widest mb-1">{stat.label}</p>
                    <h4 className="text-2xl font-black text-white leading-none">{stat.value}</h4>
                </div>
            </div>
         ))}
      </div>

      <div className="grid grid-cols-1 lg:grid-cols-2 gap-10">
          {/* ANALYTICAL PREVIEW */}
          <div className="bg-slate-950 p-10 rounded-[3.5rem] border border-white/5 shadow-2xl space-y-10">
              <div className="flex items-center justify-between">
                <div className="flex items-center gap-4">
                  <div className="bg-blue-500/10 p-3 rounded-2xl text-blue-400 shadow-sm"><Zap size={22} fill="currentColor" /></div>
                  <h4 className="text-xl font-black text-white uppercase tracking-tighter leading-none">Operational Metrics</h4>
                </div>
              </div>
              <div className="grid grid-cols-2 gap-10">
                  <div className="space-y-6 flex flex-col items-center">
                      <div className="relative w-32 h-32">
                          <svg className="w-full h-full transform -rotate-90">
                              <circle cx="64" cy="64" r="56" fill="none" stroke="rgba(255,255,255,0.05)" strokeWidth="12" />
                              <circle cx="64" cy="64" r="56" fill="none" stroke="#10B981" strokeWidth="12" strokeDasharray="351.85" strokeDashoffset={351.85 * (1 - stats.efficiency/100)} strokeLinecap="round" className="transition-all duration-1000" />
                          </svg>
                          <div className="absolute inset-0 flex flex-col items-center justify-center">
                              <span className="text-2xl font-black text-white leading-none">{stats.efficiency}%</span>
                              <span className="text-[8px] font-black text-slate-500 uppercase tracking-widest mt-1">Efficiency</span>
                          </div>
                      </div>
                      <p className="text-[10px] font-black text-slate-400 uppercase tracking-widest">Workflow Success Ratio</p>
                  </div>
                  <div className="space-y-8">
                      <div className="space-y-2">
                        <div className="flex justify-between text-[10px] font-black text-slate-500 uppercase"><span>Approved</span><span className="text-emerald-400">{stats.approved}</span></div>
                        <div className="h-1.5 bg-white/5 rounded-full overflow-hidden"><div className="h-full bg-emerald-500" style={{width: `${stats.total > 0 ? (stats.approved/stats.total)*100 : 0}%`}} /></div>
                      </div>
                      <div className="space-y-2">
                        <div className="flex justify-between text-[10px] font-black text-slate-500 uppercase"><span>Rejected</span><span className="text-red-400">{stats.rejected}</span></div>
                        <div className="h-1.5 bg-white/5 rounded-full overflow-hidden"><div className="h-full bg-red-500" style={{width: `${stats.total > 0 ? (stats.rejected/stats.total)*100 : 0}%`}} /></div>
                      </div>
                  </div>
              </div>
          </div>

          <div className="bg-slate-900/30 backdrop-blur-md rounded-[3.5rem] border border-white/5 overflow-hidden flex flex-col p-10">
              <div className="flex items-center gap-3 mb-8 border-b border-white/5 pb-6">
                  <Target size={20} className="text-indigo-400" />
                  <h4 className="text-lg font-black text-white uppercase tracking-widest">Analytics Insights</h4>
              </div>
              <div className="flex-1 flex items-center justify-center">
                  <div className="text-center space-y-4 opacity-40">
                      <BarChart3 size={60} className="mx-auto text-slate-600" />
                      <p className="text-[10px] font-black uppercase tracking-[0.4em] text-slate-400">Trend forecasting active...</p>
                  </div>
              </div>
          </div>
      </div>

      {/* DATA PREVIEW TABLE */}
      <div className="bg-slate-950 rounded-[3rem] shadow-2xl border border-white/5 overflow-hidden">
          <div className="bg-slate-900 text-white px-10 py-5 flex items-center justify-between border-b border-white/5">
              <div className="flex items-center gap-3">
                  <Activity size={18} className="text-blue-400" />
                  <h4 className="text-[11px] font-black uppercase tracking-[0.25em]">Audit Registry Stream</h4>
              </div>
              <div className="flex items-center gap-4">
                <span className="text-[10px] font-black text-slate-500 uppercase tracking-widest">Matched Records: {filteredClaims.length} Objects</span>
                <div className="w-2 h-2 rounded-full bg-emerald-500 animate-pulse" />
              </div>
          </div>
          <div className="overflow-x-auto">
              <table className="min-w-full divide-y divide-white/5 text-left">
                  <thead className="bg-slate-950">
                      <tr>
                          <th className="px-8 py-5 text-[9px] font-black text-slate-500 uppercase tracking-widest">Identity Protocol</th>
                          <th className="px-8 py-5 text-[9px] font-black text-slate-500 uppercase tracking-widest">Workflow State</th>
                          <th className="px-8 py-5 text-[9px] font-black text-slate-500 uppercase tracking-widest text-right">LKR Value</th>
                      </tr>
                  </thead>
                  <tbody className="divide-y divide-white/5 bg-slate-950">
                      {filteredClaims.length === 0 ? (
                        <tr><td colSpan={3} className="py-32 text-center text-slate-600 font-black uppercase text-xs italic">No data matched current matrix parameters</td></tr>
                      ) : (
                        filteredClaims.map(c => (
                            <tr key={c.id} className="hover:bg-white/5 transition-all duration-300">
                                <td className="px-8 py-6">
                                    <div className="text-xs font-black text-white uppercase mb-1.5">{c.customerName}</div>
                                    <div className="text-[9px] font-bold text-slate-500 uppercase tracking-tighter flex items-center gap-2">
                                        <Building2 size={10} className="text-blue-400" /> {c.company} • <MapPin size={10} /> {c.branch} • <Layers size={10} /> {c.claimType}
                                    </div>
                                </td>
                                <td className="px-8 py-6">
                                    <span className={`px-3 py-1 rounded-full text-[8px] font-black uppercase border shadow-sm flex items-center w-fit gap-1.5 ${
                                        c.status === 'Completed' ? 'bg-emerald-500/10 text-emerald-400 border-emerald-500/20' :
                                        c.status === 'Rejected' ? 'bg-red-500/10 text-red-400 border-red-500/20' :
                                        'bg-blue-500/10 text-blue-400 border-blue-500/20'
                                    }`}>
                                        <div className={`w-1.5 h-1.5 rounded-full ${
                                            c.status === 'Completed' ? 'bg-emerald-500' :
                                            c.status === 'Rejected' ? 'bg-red-500' :
                                            'bg-blue-500'
                                        }`} />
                                        {c.status}
                                    </span>
                                </td>
                                <td className="px-8 py-6 text-right font-mono font-black text-white text-sm">
                                    {c.loanAmount}
                                </td>
                            </tr>
                        ))
                      )}
                  </tbody>
              </table>
          </div>
      </div>
    </div>
  );
};

export default ReportConsole;
